print('Hellooo')
print('I\'m pd')
print('')
print('Today is Monday')
print('Now is 8O\'clock')
print('I am learning basic python\t&\tlearing Korea laugauge')
print('\n\n')
print('Thankyou Luv u')
